#!/usr/bin/env python3
"""Generate Hugo pages from DTWC++ documentation single sources of truth.

The API pages are slices of docs/api-contract-2.0.md; the UCR page is a
release-safe projection of the committed benchmark ledger; and the landing-page
snippets are escaped directly from the three executable quickstart files.
"""

from __future__ import annotations

import argparse
import html
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
CONTENT = DOCS / "content"
GENERATED = "<!-- Generated by scripts/generate_docs.py; do not hand-edit. -->\n\n"


def section(text: str, start: str, end: str | None) -> str:
    begin = re.search(rf"^## {re.escape(start)}.*$", text, re.MULTILINE)
    if begin is None:
        raise RuntimeError(f"missing contract section {start!r}")
    finish = re.search(rf"^## {re.escape(end)}.*$", text[begin.end():], re.MULTILINE) \
        if end is not None else None
    stop = begin.end() + finish.start() if finish is not None else len(text)
    return text[begin.start():stop].strip() + "\n"


def page(title: str, weight: int, body: str, description: str = "") -> str:
    desc = f'description: "{description}"\n' if description else ""
    return (
        "---\n"
        f'title: "{title}"\n'
        f"weight: {weight}\n"
        f"{desc}"
        "---\n\n"
        + GENERATED
        + body.rstrip()
        + "\n"
    )


def quickstart_card(language: str, css_language: str, source: str) -> str:
    return (
        '<section class="quickstart-card">\n'
        f"<h3>{html.escape(language)}</h3>\n"
        f'<pre tabindex="0"><code class="language-{css_language}">'
        f"{html.escape(source.rstrip())}</code></pre>\n"
        "</section>"
    )


def landing() -> str:
    cpp = (ROOT / "examples/cpp/quickstart.cpp").read_text(encoding="utf-8")
    py = (DOCS / "examples/quickstart.py").read_text(encoding="utf-8")
    matlab = (DOCS / "examples/quickstart.m").read_text(encoding="utf-8")
    cards = "\n".join((
        quickstart_card("C++", "cpp", cpp),
        quickstart_card("Python", "python", py),
        quickstart_card("MATLAB", "matlab", matlab),
    ))
    return page(
        "DTWC++",
        1,
        """# Fast, honest DTW clustering

DTWC++ provides one clustering engine across C++, Python, MATLAB, and the CLI.
It combines parallel CPU kernels, CUDA and Metal distance backends, scalable
matrix-free algorithms, exact solver routes, and loud capability checks—without
silently substituting a different device or method.

## 60-second cross-language quickstart

Each program below reads the permanent 27-series conformance fixture, runs
banded FastPAM (`k=3`, band `3`), canonicalises cluster IDs, and asserts the same
answer. The snippets are generated byte-for-byte from executable files, so the
page cannot drift from the tests.

From a repository checkout, build/run the C++ example, run the Python file, or
run the MATLAB script after placing the MEX file and `bindings/matlab` on the
MATLAB path.

<div class="quickstart-grid">
"""
        + cards
        + """
</div>

Expected output in every language:

```text
labels: 0x9 1x9 2x9
medoids: 4 13 22
mean silhouette: 0.968950
```

Continue with [installation](getting-started/installation/), the
[Tier-1 API](api/tier-1/), or [device selection](guides/devices/).
""",
        "Fast Dynamic Time Warping and clustering for C++, Python, and MATLAB.",
    )


def ucr_page(source: str) -> str:
    # Only the quiet Oxford ARC four-architecture sweep is a release benchmark.
    # Remove the later local M2 spot-check and the two M2 rows from hardware.
    source = re.sub(
        r"\n### Apple Silicon spot-check.*?(?=\n## Summary)",
        "\n",
        source,
        flags=re.DOTALL,
    )
    source = "\n".join(
        line for line in source.splitlines()
        if "Apple M2 Max" not in line
    )
    body = """# UCR archive benchmark

> Release evidence only. This page includes the committed quiet Oxford ARC
> sweep on all 128 datasets and four architectures. Local advisory profiler and
> Apple Silicon spot measurements are deliberately excluded.

""" + re.sub(r"^# UCR Archive Benchmark Results\s*", "", source).lstrip()
    return page("UCR benchmark", 10, body, "All 128 UCR datasets on four architectures.")


def generated_outputs() -> dict[Path, str]:
    contract = (DOCS / "api-contract-2.0.md").read_text(encoding="utf-8")
    tier1 = section(contract, "1.", "2.")
    tier2 = section(contract, "2.", "3.")
    migration = section(contract, "3.", "5.")
    migration += """

## Behavioural changes to check

- Series storage and CLI `--dtype` default to float64; float32 is explicit.
- C++ algorithms write labels, medoids, and `k` back into `Problem`.
- Ten C++ `Problem` fields are now private. Read `method`, `random_seed`,
  `last_iterations`, `tadpole_dc`, `lb_strategy`, `storage_policy`, `verbose`,
  `output_folder`, `name`, and `data` through same-name accessors; mutate them
  through `set_*` methods (`last_iterations` is read-only and data replacement
  uses `set_data`/`set_view_data`).
- Unsupported devices, methods, metrics, and solver backends fail loudly.
- `Result.distance_matrix` is `None` for matrix-free methods (`onebatch`,
  `clara`, and `tadpole`); code that needs an N×N matrix must request a
  matrix-based method or compute it explicitly.
- Explicit GPU requests no longer warn and run on CPU. An unavailable CUDA or
  Metal backend raises `DeviceError`; select `cpu` explicitly to run locally.
- Requesting an unavailable MIP solver no longer prints and returns. It raises
  `SolverError` before returning an empty or stale clustering result.
- OpenMP is required unless `-DDTWC_ALLOW_SEQUENTIAL=ON` is explicitly set;
  that build and a runtime one-thread cap both emit a process-once warning.
- MATLAB indices remain 1-based at its public boundary; C++ and Python are 0-based.
"""

    outputs = {
        CONTENT / "_index.md": landing(),
        CONTENT / "api/tier-1.md": page(
            "Tier 1: device, load, cluster, Result", 10, tier1,
            "Textually aligned C++, Python, and MATLAB high-level API.",
        ),
        CONTENT / "api/tier-2.md": page(
            "Tier 2: Problem and advanced APIs", 20, tier2,
            "Advanced Problem, algorithms, scores, distance, and checkpoint APIs.",
        ),
        CONTENT / "guides/migration.md": page(
            "Migrating from 1.x to 2.0", 50, migration,
            "Complete rename table, deprecations, and behavioural changes.",
        ),
        CONTENT / "benchmarks/ucr.md": ucr_page(
            (ROOT / "benchmarks/ucr_benchmark_results.md").read_text(encoding="utf-8")
        ),
    }

    contributing_sources = (
        (ROOT / "CONTRIBUTING.md", "Guideline", 2, "guideline.md"),
        (ROOT / "develop/conventions.md", "Coding conventions", 3, "conventions.md"),
        (ROOT / "develop/contributors.md", "Contributors", 4, "contributors.md"),
    )
    for source_path, title, weight, filename in contributing_sources:
        body = source_path.read_text(encoding="utf-8")
        body = re.sub(r"\A---\s*\n.*?\n---\s*\n", "", body, flags=re.DOTALL)
        body = body.replace("](develop/", "](")
        outputs[CONTENT / "contributing" / filename] = page(title, weight, body)

    # The derivation is a required tracked documentation source.  Reading it
    # unconditionally makes a missing source fail locally and in CI instead of
    # silently reducing the drift check to output-file existence.
    derivation_source = ROOT / "docs/sources/lr-core-derivation.md"
    if not derivation_source.is_file():
        raise RuntimeError(
            "missing canonical LR-core derivation source: "
            f"{derivation_source.relative_to(ROOT)}"
        )
    derivation = derivation_source.read_text(encoding="utf-8")
    plan_archive = ROOT / ".claude/PLAN-archive-2026-07-20-phases0-9.md"
    if not plan_archive.is_file():
        raise RuntimeError(
            "missing archived Phase 4 implementation record: "
            f"{plan_archive.relative_to(ROOT)}"
        )
    plan_text = plan_archive.read_text(encoding="utf-8")
    outcome = re.search(
        r"^## Phase 4 .*?(?=^## Phase 5 )",
        plan_text,
        flags=re.MULTILINE | re.DOTALL,
    )
    if outcome is None:
        raise RuntimeError(
            "missing Phase 4 implementation outcome in "
            f"{plan_archive.relative_to(ROOT)}"
        )
    outputs[CONTENT / "math/lr-core.md"] = page(
        "LR-core exact solver derivation", 10,
        """This is the complete, re-derivable solver investigation promoted
from the development report into permanent documentation. Confirmed results,
registered prediction bands, and falsified claims are retained rather than
rewritten after the implementation outcome.

""" + derivation + "\n\n## Implementation outcome and registered-band verdicts\n\n"
        + outcome.group(0).strip() + "\n",
        "Full total-unimodularity, Lagrangian, and LR-core derivation.",
    )
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if tracked generated pages are stale")
    args = parser.parse_args()

    stale: list[str] = []
    for path, expected in generated_outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != expected:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8", newline="\n")

    if stale:
        print("stale or missing generated documentation:", file=sys.stderr)
        for item in stale:
            print(f"  {item}", file=sys.stderr)
        print("run: python scripts/generate_docs.py", file=sys.stderr)
        return 1
    print("generated documentation is current" if args.check else
          "generated documentation updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
