#!/usr/bin/env python3
"""Derive tests/floors.cmake from one or more `ctest -V` logs.

A ctest -V log prefixes every test output line with "<n>: " and announces each
test with "Start <n>: <name>". Catch2 prints "All tests passed (A assertions in
C test cases)" only when nothing skipped or failed. The floor of a test is the
MINIMUM (A, C) over every log in which it printed that summary: configurations
compile different subsets of assertions (mmap, HiGHS, Arrow, OpenMP), and the
floor must hold in all of them. Tests that never printed the summary get no
entry, and dtwc_add_test() refuses to register them without an explicit floor.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

START = re.compile(r"^\s*Start\s+(\d+): (\S+)")
SUMMARY = re.compile(
    r"^(\d+): All tests passed \((\d+) assertions? in (\d+) test cases?\)")


def parse(log: Path) -> dict[str, tuple[int, int]]:
    names: dict[str, str] = {}
    floors: dict[str, tuple[int, int]] = {}
    for line in log.read_text(encoding="utf-8", errors="replace").splitlines():
        started = START.match(line)
        if started:
            names[started.group(1)] = started.group(2)
            continue
        summary = SUMMARY.match(line)
        if summary and summary.group(1) in names:
            floors[names[summary.group(1)]] = (int(summary.group(2)),
                                               int(summary.group(3)))
    return floors


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("logs", nargs="+", type=Path)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    merged: dict[str, tuple[int, int]] = {}
    for log in args.logs:
        for name, (assertions, cases) in parse(log).items():
            previous = merged.get(name)
            merged[name] = ((assertions, cases) if previous is None
                            else (min(previous[0], assertions),
                                  min(previous[1], cases)))
    if not merged:
        print("no Catch2 summaries found in the given logs", file=sys.stderr)
        return 1

    lines = [
        "# Generated by scripts/measure_test_floors.py -- do not edit by hand.",
        "# DTWC_TEST_FLOOR_<test> = \"<min assertions>;<min test cases>\" over the",
        "# ctest -V logs recorded in .claude/baselines/2026-09-07-design-2.0-W0.md.",
        "# Regenerate after a deliberate test change:",
        "#   uv run --no-project python scripts/measure_test_floors.py <logs...> --out tests/floors.cmake",
        "",
    ]
    for name in sorted(merged):
        assertions, cases = merged[name]
        lines.append(f'set(DTWC_TEST_FLOOR_{name} "{assertions};{cases}")')
    args.out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"TEST_FLOORS tests={len(merged)} logs={len(args.logs)} out={args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
