title: DTWC++
description: Official documentation of DTWpp software.
remote_theme: Battery-Intelligence-Lab/bil-jekyll-rtd-theme

# Theme settings:
site_author: DTWC++ authors
repo_url: "https://github.com/Battery-Intelligence-Lab/dtw-cpp/"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
