name: macOS unit
# adapted from: https://github.com/trase-cpp/trase/tree/master/.github/workflows
on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: macOS unit
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6
      
      - name: Install dependencies
        run: |
          brew install ninja libomp
          brew link --force libomp

      - name: CMake configure (Release with HiGHS)
        run: |
          cmake --preset clang-macos -DDTWC_BUILD_TESTING=ON -DDTWC_ENABLE_HIGHS=ON

      - name: CMake build
        run: |
          cmake --build build --config Release --parallel

      - name: CMake test
        run: |
          ctest --test-dir build -j -C Release --output-on-failure